# Fichier de configuration
#APP
HOST: 0.0.0.0
PORT: 5000

#DATABASE
NAME_DB: db_diagnostic_distant
USER_DB: souxateuserprod
PASSWORD_DB: S0ux@t3Pr0d2021
HOST_DB: 10.137.15.70
PORT_DB: 5432

#INTEGRATION DE KEYCLOACK
REALM: network
CLIENT_ID: rest-client
CLIENT_SECRET: 48e70a98-b84f-49f6-8e99-495cacafa00e
GRANT_TYPE: client_credentials
URI_BASE: "http://localhost:8080/auth/"
URI: "http://localhost:8080/auth/realms/network/protocol/openid-connect/token"
URI_USER: "http://localhost:8080/auth/admin/realms/network/users"
URI_ROLES: "http://localhost:8080/auth/admin/realms/network/roles"

