# Fichier de configuration

#INTEGRATION DE KEYCLOACK
REALM: network
CLIENT_ID: rest-client
CLIENT_SECRET: 48e70a98-b84f-49f6-8e99-495cacafa00e
GRANT_TYPE: client_credentials
URI_BASE: "http://localhost:8080/auth/"
URI: "http://localhost:8080/auth/realms/network/protocol/openid-connect/token"
URI_USER: "http://localhost:8080/auth/admin/realms/network/users"
URI_ROLES: "http://localhost:8080/auth/admin/realms/network/roles"

